# Generated by Django 3.0.6 on 2020-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('Qualifications', models.TextField(max_length=500)),
                ('Skills', models.TextField(max_length=500)),
                ('currently_working_as', models.CharField(max_length=50)),
                ('About', models.TextField(max_length=1000)),
                ('img', models.ImageField(upload_to='author/images')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
