# Generated by Django 3.0.6 on 2020-05-21 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blg_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technology', 'TECHNOLOGY'), ('Culture', 'CULTURE'), ('Business', 'BUSINESS'), ('Politics', 'POLITICS'), ('Opinion', 'OPINION'), ('Food', 'FOOD'), ('Education', 'EDUCATION'), ('Science', 'SCIENCE'), ('Health', 'HEALTH'), ('Style', 'STYLE'), ('Travel', 'TRAVEL'), ('Others', 'OTHERS')], max_length=20)),
                ('blog_description_1', models.TextField(max_length=5000)),
                ('blog_description_2', models.TextField(max_length=5000)),
                ('sub_heading_optional', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_description_optional', models.TextField(blank=True, max_length=5000, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
                ('link_optional', models.URLField(blank=True, null=True)),
                ('link_name_optional', models.CharField(blank=True, max_length=70, null=True)),
                ('img', models.ImageField(upload_to='content/images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Author')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('mob', models.CharField(max_length=50)),
                ('textarea', models.TextField(default='', max_length=10000)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='URL_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_name', models.CharField(max_length=100)),
                ('url_embed', models.URLField()),
            ],
            options={
                'verbose_name': 'URL_update',
                'verbose_name_plural': 'URL_updates',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Blog')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.BlogComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BlogComment',
                'verbose_name_plural': 'BlogComments',
            },
        ),
    ]
